
import 'package:fluttericon/brandico_icons.dart';
import '../example_icon.dart';

// NB: DO NOT EDIT! This file is auto-generated. See util/gen_examples.dart

final brandico_icons = <ExampleIcon>[
    ExampleIcon(Brandico.facebook_1, "Brandico", "facebook_1"),
    ExampleIcon(Brandico.facebook_rect, "Brandico", "facebook_rect"),
    ExampleIcon(Brandico.twitter_1, "Brandico", "twitter_1"),
    ExampleIcon(Brandico.twitter_bird, "Brandico", "twitter_bird"),
    ExampleIcon(Brandico.vimeo_1, "Brandico", "vimeo_1"),
    ExampleIcon(Brandico.vimeo_rect, "Brandico", "vimeo_rect"),
    ExampleIcon(Brandico.tumblr_1, "Brandico", "tumblr_1"),
    ExampleIcon(Brandico.tumblr_rect, "Brandico", "tumblr_rect"),
    ExampleIcon(Brandico.googleplus_rect, "Brandico", "googleplus_rect"),
    ExampleIcon(Brandico.github_text, "Brandico", "github_text"),
    ExampleIcon(Brandico.github_1, "Brandico", "github_1"),
    ExampleIcon(Brandico.skype_1, "Brandico", "skype_1"),
    ExampleIcon(Brandico.icq, "Brandico", "icq"),
    ExampleIcon(Brandico.yandex, "Brandico", "yandex"),
    ExampleIcon(Brandico.yandex_rect, "Brandico", "yandex_rect"),
    ExampleIcon(Brandico.vkontakte_rect, "Brandico", "vkontakte_rect"),
    ExampleIcon(Brandico.odnoklassniki, "Brandico", "odnoklassniki"),
    ExampleIcon(Brandico.odnoklassniki_rect, "Brandico", "odnoklassniki_rect"),
    ExampleIcon(Brandico.friendfeed, "Brandico", "friendfeed"),
    ExampleIcon(Brandico.friendfeed_rect, "Brandico", "friendfeed_rect"),
    ExampleIcon(Brandico.blogger_1, "Brandico", "blogger_1"),
    ExampleIcon(Brandico.blogger_rect, "Brandico", "blogger_rect"),
    ExampleIcon(Brandico.deviantart, "Brandico", "deviantart"),
    ExampleIcon(Brandico.jabber, "Brandico", "jabber"),
    ExampleIcon(Brandico.lastfm_1, "Brandico", "lastfm_1"),
    ExampleIcon(Brandico.lastfm_rect, "Brandico", "lastfm_rect"),
    ExampleIcon(Brandico.linkedin_1, "Brandico", "linkedin_1"),
    ExampleIcon(Brandico.linkedin_rect, "Brandico", "linkedin_rect"),
    ExampleIcon(Brandico.picasa, "Brandico", "picasa"),
    ExampleIcon(Brandico.wordpress_1, "Brandico", "wordpress_1"),
    ExampleIcon(Brandico.instagram_1, "Brandico", "instagram_1"),
    ExampleIcon(Brandico.instagram_filled, "Brandico", "instagram_filled"),
    ExampleIcon(Brandico.diigo, "Brandico", "diigo"),
    ExampleIcon(Brandico.box, "Brandico", "box"),
    ExampleIcon(Brandico.box_rect, "Brandico", "box_rect"),
    ExampleIcon(Brandico.tudou, "Brandico", "tudou"),
    ExampleIcon(Brandico.youku, "Brandico", "youku"),
    ExampleIcon(Brandico.win8, "Brandico", "win8"),
    ExampleIcon(Brandico.amex, "Brandico", "amex"),
    ExampleIcon(Brandico.discover, "Brandico", "discover"),
    ExampleIcon(Brandico.visa, "Brandico", "visa"),
    ExampleIcon(Brandico.mastercard, "Brandico", "mastercard"),
    ExampleIcon(Brandico.houzz, "Brandico", "houzz"),
    ExampleIcon(Brandico.bandcamp, "Brandico", "bandcamp"),
    ExampleIcon(Brandico.codepen, "Brandico", "codepen"),
];