
import 'package:fluttericon/linecons_icons.dart';
import '../example_icon.dart';

// NB: DO NOT EDIT! This file is auto-generated. See util/gen_examples.dart

final linecons_icons = <ExampleIcon>[
    ExampleIcon(Linecons.music, "Linecons", "music"),
    ExampleIcon(Linecons.search, "Linecons", "search"),
    ExampleIcon(Linecons.mail, "Linecons", "mail"),
    ExampleIcon(Linecons.heart, "Linecons", "heart"),
    ExampleIcon(Linecons.star, "Linecons", "star"),
    ExampleIcon(Linecons.user, "Linecons", "user"),
    ExampleIcon(Linecons.videocam, "Linecons", "videocam"),
    ExampleIcon(Linecons.camera, "Linecons", "camera"),
    ExampleIcon(Linecons.photo, "Linecons", "photo"),
    ExampleIcon(Linecons.attach, "Linecons", "attach"),
    ExampleIcon(Linecons.lock, "Linecons", "lock"),
    ExampleIcon(Linecons.eye, "Linecons", "eye"),
    ExampleIcon(Linecons.tag, "Linecons", "tag"),
    ExampleIcon(Linecons.thumbs_up, "Linecons", "thumbs_up"),
    ExampleIcon(Linecons.pencil, "Linecons", "pencil"),
    ExampleIcon(Linecons.comment, "Linecons", "comment"),
    ExampleIcon(Linecons.location, "Linecons", "location"),
    ExampleIcon(Linecons.cup, "Linecons", "cup"),
    ExampleIcon(Linecons.trash, "Linecons", "trash"),
    ExampleIcon(Linecons.doc, "Linecons", "doc"),
    ExampleIcon(Linecons.note, "Linecons", "note"),
    ExampleIcon(Linecons.cog, "Linecons", "cog"),
    ExampleIcon(Linecons.params, "Linecons", "params"),
    ExampleIcon(Linecons.calendar, "Linecons", "calendar"),
    ExampleIcon(Linecons.sound, "Linecons", "sound"),
    ExampleIcon(Linecons.clock, "Linecons", "clock"),
    ExampleIcon(Linecons.lightbulb, "Linecons", "lightbulb"),
    ExampleIcon(Linecons.tv, "Linecons", "tv"),
    ExampleIcon(Linecons.desktop, "Linecons", "desktop"),
    ExampleIcon(Linecons.mobile, "Linecons", "mobile"),
    ExampleIcon(Linecons.cd, "Linecons", "cd"),
    ExampleIcon(Linecons.inbox, "Linecons", "inbox"),
    ExampleIcon(Linecons.globe, "Linecons", "globe"),
    ExampleIcon(Linecons.cloud, "Linecons", "cloud"),
    ExampleIcon(Linecons.paper_plane, "Linecons", "paper_plane"),
    ExampleIcon(Linecons.fire, "Linecons", "fire"),
    ExampleIcon(Linecons.graduation_cap, "Linecons", "graduation_cap"),
    ExampleIcon(Linecons.megaphone, "Linecons", "megaphone"),
    ExampleIcon(Linecons.database, "Linecons", "database"),
    ExampleIcon(Linecons.key, "Linecons", "key"),
    ExampleIcon(Linecons.beaker, "Linecons", "beaker"),
    ExampleIcon(Linecons.truck, "Linecons", "truck"),
    ExampleIcon(Linecons.money, "Linecons", "money"),
    ExampleIcon(Linecons.food, "Linecons", "food"),
    ExampleIcon(Linecons.shop, "Linecons", "shop"),
    ExampleIcon(Linecons.diamond, "Linecons", "diamond"),
    ExampleIcon(Linecons.t_shirt, "Linecons", "t_shirt"),
    ExampleIcon(Linecons.wallet, "Linecons", "wallet"),
];