
import 'package:fluttericon/maki_icons.dart';
import '../example_icon.dart';

// NB: DO NOT EDIT! This file is auto-generated. See util/gen_examples.dart

final maki_icons = <ExampleIcon>[
    ExampleIcon(Maki.aboveground_rail, "Maki", "aboveground_rail"),
    ExampleIcon(Maki.airfield, "Maki", "airfield"),
    ExampleIcon(Maki.airport, "Maki", "airport"),
    ExampleIcon(Maki.art_gallery, "Maki", "art_gallery"),
    ExampleIcon(Maki.bar, "Maki", "bar"),
    ExampleIcon(Maki.baseball, "Maki", "baseball"),
    ExampleIcon(Maki.basketball, "Maki", "basketball"),
    ExampleIcon(Maki.beer, "Maki", "beer"),
    ExampleIcon(Maki.belowground_rail, "Maki", "belowground_rail"),
    ExampleIcon(Maki.bicycle, "Maki", "bicycle"),
    ExampleIcon(Maki.bus, "Maki", "bus"),
    ExampleIcon(Maki.cafe, "Maki", "cafe"),
    ExampleIcon(Maki.campsite, "Maki", "campsite"),
    ExampleIcon(Maki.cemetery, "Maki", "cemetery"),
    ExampleIcon(Maki.cinema, "Maki", "cinema"),
    ExampleIcon(Maki.college, "Maki", "college"),
    ExampleIcon(Maki.commerical_building, "Maki", "commerical_building"),
    ExampleIcon(Maki.credit_card, "Maki", "credit_card"),
    ExampleIcon(Maki.cricket, "Maki", "cricket"),
    ExampleIcon(Maki.embassy, "Maki", "embassy"),
    ExampleIcon(Maki.fast_food, "Maki", "fast_food"),
    ExampleIcon(Maki.ferry, "Maki", "ferry"),
    ExampleIcon(Maki.fire_station, "Maki", "fire_station"),
    ExampleIcon(Maki.football, "Maki", "football"),
    ExampleIcon(Maki.fuel, "Maki", "fuel"),
    ExampleIcon(Maki.garden, "Maki", "garden"),
    ExampleIcon(Maki.giraffe, "Maki", "giraffe"),
    ExampleIcon(Maki.golf, "Maki", "golf"),
    ExampleIcon(Maki.grocery_store, "Maki", "grocery_store"),
    ExampleIcon(Maki.harbor, "Maki", "harbor"),
    ExampleIcon(Maki.heliport, "Maki", "heliport"),
    ExampleIcon(Maki.hospital, "Maki", "hospital"),
    ExampleIcon(Maki.industrial_building, "Maki", "industrial_building"),
    ExampleIcon(Maki.library_icon, "Maki", "library_icon"),
    ExampleIcon(Maki.lodging, "Maki", "lodging"),
    ExampleIcon(Maki.london_underground, "Maki", "london_underground"),
    ExampleIcon(Maki.minefield, "Maki", "minefield"),
    ExampleIcon(Maki.monument, "Maki", "monument"),
    ExampleIcon(Maki.museum, "Maki", "museum"),
    ExampleIcon(Maki.pharmacy, "Maki", "pharmacy"),
    ExampleIcon(Maki.pitch, "Maki", "pitch"),
    ExampleIcon(Maki.police, "Maki", "police"),
    ExampleIcon(Maki.post, "Maki", "post"),
    ExampleIcon(Maki.prison, "Maki", "prison"),
    ExampleIcon(Maki.rail, "Maki", "rail"),
    ExampleIcon(Maki.religious_christian, "Maki", "religious_christian"),
    ExampleIcon(Maki.religious_islam, "Maki", "religious_islam"),
    ExampleIcon(Maki.religious_jewish, "Maki", "religious_jewish"),
    ExampleIcon(Maki.restaurant, "Maki", "restaurant"),
    ExampleIcon(Maki.roadblock, "Maki", "roadblock"),
    ExampleIcon(Maki.school, "Maki", "school"),
    ExampleIcon(Maki.shop, "Maki", "shop"),
    ExampleIcon(Maki.skiing, "Maki", "skiing"),
    ExampleIcon(Maki.soccer, "Maki", "soccer"),
    ExampleIcon(Maki.swimming, "Maki", "swimming"),
    ExampleIcon(Maki.tennis, "Maki", "tennis"),
    ExampleIcon(Maki.theatre, "Maki", "theatre"),
    ExampleIcon(Maki.toilet, "Maki", "toilet"),
    ExampleIcon(Maki.town_hall, "Maki", "town_hall"),
    ExampleIcon(Maki.trash, "Maki", "trash"),
    ExampleIcon(Maki.tree_1, "Maki", "tree_1"),
    ExampleIcon(Maki.tree_2, "Maki", "tree_2"),
    ExampleIcon(Maki.warehouse, "Maki", "warehouse"),
];