
import 'package:fluttericon/meteocons_icons.dart';
import '../example_icon.dart';

// NB: DO NOT EDIT! This file is auto-generated. See util/gen_examples.dart

final meteocons_icons = <ExampleIcon>[
    ExampleIcon(Meteocons.windy_rain_inv, "Meteocons", "windy_rain_inv"),
    ExampleIcon(Meteocons.snow_inv, "Meteocons", "snow_inv"),
    ExampleIcon(Meteocons.snow_heavy_inv, "Meteocons", "snow_heavy_inv"),
    ExampleIcon(Meteocons.hail_inv, "Meteocons", "hail_inv"),
    ExampleIcon(Meteocons.clouds_inv, "Meteocons", "clouds_inv"),
    ExampleIcon(Meteocons.clouds_flash_inv, "Meteocons", "clouds_flash_inv"),
    ExampleIcon(Meteocons.temperature, "Meteocons", "temperature"),
    ExampleIcon(Meteocons.compass, "Meteocons", "compass"),
    ExampleIcon(Meteocons.na, "Meteocons", "na"),
    ExampleIcon(Meteocons.celcius, "Meteocons", "celcius"),
    ExampleIcon(Meteocons.fahrenheit, "Meteocons", "fahrenheit"),
    ExampleIcon(Meteocons.clouds_flash_alt, "Meteocons", "clouds_flash_alt"),
    ExampleIcon(Meteocons.sun_inv, "Meteocons", "sun_inv"),
    ExampleIcon(Meteocons.moon_inv, "Meteocons", "moon_inv"),
    ExampleIcon(Meteocons.cloud_sun_inv, "Meteocons", "cloud_sun_inv"),
    ExampleIcon(Meteocons.cloud_moon_inv, "Meteocons", "cloud_moon_inv"),
    ExampleIcon(Meteocons.cloud_inv, "Meteocons", "cloud_inv"),
    ExampleIcon(Meteocons.cloud_flash_inv, "Meteocons", "cloud_flash_inv"),
    ExampleIcon(Meteocons.drizzle_inv, "Meteocons", "drizzle_inv"),
    ExampleIcon(Meteocons.rain_inv, "Meteocons", "rain_inv"),
    ExampleIcon(Meteocons.windy_inv, "Meteocons", "windy_inv"),
    ExampleIcon(Meteocons.sunrise, "Meteocons", "sunrise"),
    ExampleIcon(Meteocons.sun, "Meteocons", "sun"),
    ExampleIcon(Meteocons.moon, "Meteocons", "moon"),
    ExampleIcon(Meteocons.eclipse, "Meteocons", "eclipse"),
    ExampleIcon(Meteocons.mist, "Meteocons", "mist"),
    ExampleIcon(Meteocons.wind, "Meteocons", "wind"),
    ExampleIcon(Meteocons.snowflake, "Meteocons", "snowflake"),
    ExampleIcon(Meteocons.cloud_sun, "Meteocons", "cloud_sun"),
    ExampleIcon(Meteocons.cloud_moon, "Meteocons", "cloud_moon"),
    ExampleIcon(Meteocons.fog_sun, "Meteocons", "fog_sun"),
    ExampleIcon(Meteocons.fog_moon, "Meteocons", "fog_moon"),
    ExampleIcon(Meteocons.fog_cloud, "Meteocons", "fog_cloud"),
    ExampleIcon(Meteocons.fog, "Meteocons", "fog"),
    ExampleIcon(Meteocons.cloud, "Meteocons", "cloud"),
    ExampleIcon(Meteocons.cloud_flash, "Meteocons", "cloud_flash"),
    ExampleIcon(Meteocons.cloud_flash_alt, "Meteocons", "cloud_flash_alt"),
    ExampleIcon(Meteocons.drizzle, "Meteocons", "drizzle"),
    ExampleIcon(Meteocons.rain, "Meteocons", "rain"),
    ExampleIcon(Meteocons.windy, "Meteocons", "windy"),
    ExampleIcon(Meteocons.windy_rain, "Meteocons", "windy_rain"),
    ExampleIcon(Meteocons.snow, "Meteocons", "snow"),
    ExampleIcon(Meteocons.snow_alt, "Meteocons", "snow_alt"),
    ExampleIcon(Meteocons.snow_heavy, "Meteocons", "snow_heavy"),
    ExampleIcon(Meteocons.hail, "Meteocons", "hail"),
    ExampleIcon(Meteocons.clouds, "Meteocons", "clouds"),
    ExampleIcon(Meteocons.clouds_flash, "Meteocons", "clouds_flash"),
];