/// Flutter icons Elusive
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Elusive
///      fonts:
///       - asset: fonts/Elusive.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class Elusive {
  Elusive._();

  static const _kFontFam = 'Elusive';
  static const _kFontPkg = "fluttericon";

  static const IconData glass =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_circled =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_circled =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_circled =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_circled =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_circled =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torso =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_circled =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_alt =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_chat =
      const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture =
      const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_circled =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list =
      const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_mode =
      const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok =
      const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled =
      const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled2 =
      const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel =
      const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled =
      const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled2 =
      const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled =
      const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circled =
      const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help =
      const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled =
      const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled =
      const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_circled =
      const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website =
      const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website_circled =
      const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach =
      const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_circled =
      const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_circled =
      const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open =
      const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt =
      const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off =
      const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags =
      const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_empty =
      const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_circled =
      const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up =
      const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down =
      const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_alt =
      const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload =
      const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote =
      const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_circled =
      const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon =
      const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil =
      const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_circled =
      const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      const IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_circled =
      const IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_alt =
      const IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print =
      const IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet =
      const IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      const IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt =
      const IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell =
      const IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning =
      const IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation =
      const IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error =
      const IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error_alt =
      const IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      const IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_circled =
      const IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass =
      const IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass_circled =
      const IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      const IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_circled =
      const IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc =
      const IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_circled =
      const IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_new =
      const IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_new_circled =
      const IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      const IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_circled =
      const IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_close =
      const IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open =
      const IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss =
      const IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone =
      const IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_circled =
      const IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog =
      const IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_circled =
      const IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs =
      const IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench =
      const IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench_circled =
      const IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket =
      const IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_circled =
      const IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      const IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_circled =
      const IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic =
      const IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_circled =
      const IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off =
      const IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down =
      const IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume =
      const IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up =
      const IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones =
      const IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      const IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_circled =
      const IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb =
      const IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb_alt =
      const IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block =
      const IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full =
      const IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full_alt =
      const IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small =
      const IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_vertical =
      const IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_horizontal =
      const IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move =
      const IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in =
      const IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out =
      const IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open =
      const IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open =
      const IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open =
      const IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open =
      const IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down =
      const IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left =
      const IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right =
      const IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up =
      const IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circled =
      const IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circled =
      const IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circled =
      const IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circled =
      const IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_hand =
      const IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_hand =
      const IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_hand =
      const IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_hand =
      const IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw =
      const IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw_circled =
      const IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_cw =
      const IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle =
      const IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      const IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circled =
      const IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circled2 =
      const IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      const IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_circled =
      const IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause =
      const IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_circled =
      const IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record =
      const IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject =
      const IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward =
      const IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_circled =
      const IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward =
      const IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward =
      const IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward =
      const IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_circled =
      const IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_backward =
      const IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_forward =
      const IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target =
      const IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal =
      const IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop =
      const IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_circled =
      const IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop =
      const IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_circled =
      const IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network =
      const IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox =
      const IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_circled =
      const IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_alt =
      const IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      const IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_alt =
      const IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      const IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_circled =
      const IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight =
      const IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf =
      const IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font =
      const IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fontsize =
      const IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold =
      const IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic =
      const IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_height =
      const IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_width =
      const IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left =
      const IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_center =
      const IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right =
      const IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_justify =
      const IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list =
      const IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_left =
      const IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_right =
      const IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase =
      const IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData off =
      const IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData road =
      const IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode =
      const IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode =
      const IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData braille =
      const IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      const IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjust =
      const IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tint =
      const IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      const IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_empty =
      const IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asterisk =
      const IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift =
      const IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire =
      const IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnet =
      const IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart =
      const IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_circled =
      const IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card =
      const IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone =
      const IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard =
      const IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd =
      const IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      const IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate =
      const IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks =
      const IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      const IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gauge =
      const IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley =
      const IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley_circled =
      const IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book =
      const IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book_alt =
      const IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asl =
      const IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glasses =
      const IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearing_impaired =
      const IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iphone_home =
      const IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person =
      const IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adult =
      const IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child =
      const IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blind =
      const IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guidedog =
      const IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessibility =
      const IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData universal_access =
      const IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male =
      const IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female =
      const IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance =
      const IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger =
      const IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc =
      const IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData css =
      const IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delicious =
      const IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantart =
      const IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digg =
      const IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble =
      const IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      const IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr =
      const IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foursquare =
      const IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendfeed =
      const IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendfeed_rect =
      const IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      const IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_text =
      const IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplus =
      const IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      const IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      const IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path =
      const IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picasa =
      const IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest =
      const IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit =
      const IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype =
      const IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slideshare =
      const IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow =
      const IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon =
      const IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      const IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr =
      const IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo =
      const IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vkontakte =
      const IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w3c =
      const IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wordpress =
      const IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      const IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
