/// Flutter icons Fontelico
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fontelico
///      fonts:
///       - asset: fonts/Fontelico.ttf
///
///
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class Fontelico {
  Fontelico._();

  static const _kFontFam = 'Fontelico';
  static const _kFontPkg = "fluttericon";

  static const IconData emo_happy =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_wink =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_unhappy =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sleep =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_thumbsup =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_devil =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_surprised =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_tongue =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_coffee =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sunglasses =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_displeased =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_beer =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_grin =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_angry =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_saint =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_cry =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_shoot =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_squint =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_laugh =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_wink2 =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin1 =
      const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin2 =
      const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin3 =
      const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin4 =
      const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin5 =
      const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin6 =
      const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefox =
      const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome =
      const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opera =
      const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ie =
      const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown =
      const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown_plus =
      const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown_minus =
      const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marquee =
      const IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
