/// Flutter icons Iconic
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconic
///      fonts:
///       - asset: fonts/Iconic.ttf
///
///
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class Iconic {
  Iconic._();

  static const _kFontFam = 'Iconic';
  static const _kFontPkg = "fluttericon";

  static const IconData search = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circle = const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circle = const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle = const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circle = const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_empty = const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_empty = const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_empty = const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cloud = const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_cloud = const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_left = const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_right = const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_left_alt = const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_right_alt = const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_neg = const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt = const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_inv = const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt = const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_inv_alt = const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt2 = const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_inv_alt2 = const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_inv = const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_inv = const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_alt = const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_empty = const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_inv = const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_alt = const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_inv_alt = const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article = const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article_alt = const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_open = const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss = const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_alt = const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = const IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_inv = const IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alt = const IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = const IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = const IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = const IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones = const IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = const IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp = const IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = const IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full = const IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full_alt = const IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small = const IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small_alt = const IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_vertical = const IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_horizontal = const IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move = const IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popup = const IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = const IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = const IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = const IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = const IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circle = const IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circle = const IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circle = const IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circle = const IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw = const IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop = const IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop_alt = const IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange = const IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData split = const IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_curved = const IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = const IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle2 = const IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = const IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = const IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_start = const IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_end = const IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject = const IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target = const IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = const IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = const IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_empty = const IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = const IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_nested = const IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_empty = const IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_half = const IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_full = const IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_charge = const IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = const IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd = const IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equalizer = const IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cursor = const IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aperture = const IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aperture_alt = const IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steering_wheel = const IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = const IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_alt = const IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = const IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_alt = const IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyedropper = const IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers = const IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers_alt = const IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = const IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_inv = const IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = const IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = const IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = const IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = const IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_inv = const IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella = const IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = const IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = const IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie_alt = const IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = const IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_inv = const IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hash = const IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = const IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pilcrow = const IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dial = const IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
