/// Flutter icons LineariconsFree
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LineariconsFree
///      fonts:
///       - asset: fonts/LineariconsFree.ttf
///
///
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
///
import 'package:flutter/widgets.dart';

class LineariconsFree {
  LineariconsFree._();

  static const _kFontFam = 'LineariconsFree';
  static const _kFontPkg = "fluttericon";

  static const IconData direction_ltr = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_rtl = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData page_break = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alpha_asc = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_asc = const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand = const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer_up = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer_right = const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer_down = const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer_left = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = const IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apartment = const IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = const IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic_wand = const IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop = const IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lighter = const IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poop = const IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = const IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = const IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_2 = const IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload = const IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_download = const IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sync = const IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_check = const IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database_1 = const IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 = const IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_2 = const IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = const IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = const IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1 = const IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_1 = const IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half = const IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty = const IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = const IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = const IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperclip = const IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_1 = const IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = const IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer = const IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_empty = const IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_add = const IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter = const IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = const IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_hat = const IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData license = const IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_note = const IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData film_play = const IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_video = const IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = const IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_1 = const IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = const IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = const IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = const IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = const IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shirt = const IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = const IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = const IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_1 = const IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_handset = const IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = const IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pushpin = const IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker = const IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = const IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = const IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_full = const IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard = const IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spell_check = const IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen = const IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone = const IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet = const IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = const IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_phone = const IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_swtich = const IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lnr_bubble = const IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_pulse = const IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData construction = const IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart = const IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bars = const IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = const IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_1 = const IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linearicons = const IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dinner = const IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_cup = const IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf = const IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw = const IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket = const IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = const IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = const IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = const IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = const IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = const IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelchair = const IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select = const IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth = const IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = const IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad = const IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData neutral = const IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mustache = const IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm = const IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullhorn = const IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_high = const IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_medium = const IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_low = const IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume = const IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = const IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = const IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = const IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = const IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_icon = const IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = const IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_2 = const IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = const IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = const IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter_down = const IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit_up = const IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug = const IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_1 = const IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_1 = const IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlink = const IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = const IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down = const IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifier = const IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = const IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = const IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_1 = const IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = const IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = const IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = const IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = const IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = const IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = const IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = const IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = const IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move = const IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = const IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_circle = const IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_circle = const IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark_cicle = const IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_circle = const IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle_1 = const IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_minus = const IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_circle = const IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_circle = const IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_circle = const IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_circle = const IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up_circle = const IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down_circle = const IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left_circle = const IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right_circle = const IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crop = const IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_expand = const IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_contract = const IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers = const IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel = const IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_format = const IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_format_remove = const IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_size = const IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = const IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic = const IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underline = const IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikethrough = const IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlight = const IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_left = const IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_center = const IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_right = const IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_justify = const IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_spacing = const IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_increase = const IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_decrease = const IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pilcrow = const IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vkontakte_rect = const IconData(0xf30a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype = const IconData(0xf30b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData odnoklassniki_rect = const IconData(0xf30d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_rect = const IconData(0xf312, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = const IconData(0xf313, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
