/// Flutter icons Linecons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Linecons
///      fonts:
///       - asset: fonts/Linecons.ttf
///
///
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class Linecons {
  Linecons._();

  static const _kFontFam = 'Linecons';
  static const _kFontPkg = "fluttericon";

  static const IconData music =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note =
      const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog =
      const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData params =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv =
      const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop =
      const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile =
      const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd =
      const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox =
      const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane =
      const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire =
      const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_cap =
      const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone =
      const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database =
      const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaker =
      const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck =
      const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money =
      const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food =
      const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop =
      const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond =
      const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt =
      const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet =
      const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
