/// Flutter icons Maki
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Maki
///      fonts:
///       - asset: fonts/Maki.ttf
///
///
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class Maki {
  Maki._();

  static const _kFontFam = 'Maki';
  static const _kFontPkg = "fluttericon";

  static const IconData aboveground_rail =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airfield =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airport =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData art_gallery =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData belowground_rail =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campsite =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cemetery =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cinema =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData college =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commerical_building =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData embassy =
      const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_food =
      const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ferry =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire_station =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fuel =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData garden =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giraffe =
      const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf =
      const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grocery_store =
      const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData harbor =
      const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heliport =
      const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital =
      const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData industrial_building =
      const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_icon =
      const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lodging =
      const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData london_underground =
      const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minefield =
      const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monument =
      const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData museum =
      const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pharmacy =
      const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pitch =
      const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData police =
      const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData post =
      const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prison =
      const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rail =
      const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_christian =
      const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_islam =
      const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_jewish =
      const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant =
      const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roadblock =
      const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school =
      const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop =
      const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skiing =
      const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer =
      const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming =
      const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis =
      const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theatre =
      const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toilet =
      const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData town_hall =
      const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_1 =
      const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_2 =
      const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warehouse =
      const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
