/// Flutter icons MfgLabs
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MfgLabs
///      fonts:
///       - asset: fonts/MfgLabs.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MfgLabs {
  MfgLabs._();

  static const _kFontFam = 'MfgLabs';
  static const _kFontPkg = "fluttericon";

  static const IconData mail = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled = const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled_alt = const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention_alt = const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch = const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_bold = const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_bold = const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_bold = const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_bold = const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_fat = const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_fat = const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_fat = const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_fat = const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_pencil = const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData king = const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anchor = const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = const IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open = const IconData(0xf005, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = const IconData(0xf006, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = const IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = const IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = const IconData(0xf009, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb = const IconData(0xf00a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb_empty = const IconData(0xf00b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coverflow = const IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coverflow_empty = const IconData(0xf00d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = const IconData(0xf00e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = const IconData(0xf00f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_end = const IconData(0xf010, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_start = const IconData(0xf011, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = const IconData(0xf012, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward = const IconData(0xf013, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_cloud = const IconData(0xf014, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cloud = const IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_science = const IconData(0xf016, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_science_inv = const IconData(0xf017, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = const IconData(0xf018, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_inv = const IconData(0xf019, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math = const IconData(0xf01a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math_circled_empty = const IconData(0xf01b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math_circled = const IconData(0xf01c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = const IconData(0xf01d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_alt2 = const IconData(0xf01e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_alt = const IconData(0xf01f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_adjust = const IconData(0xf020, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half = const IconData(0xf022, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half_empty = const IconData(0xf024, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccw = const IconData(0xf025, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_broken = const IconData(0xf028, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hash = const IconData(0xf029, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply = const IconData(0xf02a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet = const IconData(0xf02b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = const IconData(0xf02c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = const IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = const IconData(0xf02e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = const IconData(0xf02f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = const IconData(0xf031, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor = const IconData(0xf032, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet = const IconData(0xf033, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = const IconData(0xf034, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connected_object = const IconData(0xf035, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData isight = const IconData(0xf039, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = const IconData(0xf03a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = const IconData(0xf03b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = const IconData(0xf03d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = const IconData(0xf03f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie = const IconData(0xf040, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler = const IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = const IconData(0xf045, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_off = const IconData(0xf047, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = const IconData(0xf048, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = const IconData(0xf04a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble_circled = const IconData(0xf04f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble = const IconData(0xf050, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_circled = const IconData(0xf051, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = const IconData(0xf052, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled_alt = const IconData(0xf053, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled = const IconData(0xf054, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = const IconData(0xf055, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled_alt2 = const IconData(0xf056, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_circled = const IconData(0xf057, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = const IconData(0xf058, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus_circled = const IconData(0xf059, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus = const IconData(0xf05a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_circled = const IconData(0xf05b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = const IconData(0xf05c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = const IconData(0xf05d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_circled = const IconData(0xf05e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mfg_logo = const IconData(0xf05f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mfg_logo_circled = const IconData(0xf060, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = const IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_male = const IconData(0xf062, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_female = const IconData(0xf063, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = const IconData(0xf064, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = const IconData(0xf067, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open = const IconData(0xf068, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = const IconData(0xf069, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = const IconData(0xf06a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = const IconData(0xf06d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled = const IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = const IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = const IconData(0xf074, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt = const IconData(0xf075, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = const IconData(0xf07b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in = const IconData(0xf07e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out = const IconData(0xf07f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = const IconData(0xf080, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = const IconData(0xf081, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = const IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = const IconData(0xf083, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd = const IconData(0xf084, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = const IconData(0xf085, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled_alt = const IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = const IconData(0xf087, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fontsize = const IconData(0xf088, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud = const IconData(0xf089, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud_circled = const IconData(0xf08a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = const IconData(0xf4ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open_empty = const IconData(0xf4c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = const IconData(0xf4c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = const IconData(0xf4f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = const IconData(0xf4f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = const IconData(0xf50d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_alt = const IconData(0xf510, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = const IconData(0xf512, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = const IconData(0xf513, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joystick = const IconData(0xf514, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = const IconData(0xf525, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = const IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spread = const IconData(0xf527, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner1 = const IconData(0xf528, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner2 = const IconData(0xf529, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
