/// Flutter icons ModernPictograms
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ModernPictograms
///      fonts:
///       - asset: fonts/ModernPictograms.ttf
///
///
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
///
import 'package:flutter/widgets.dart';

class ModernPictograms {
  ModernPictograms._();

  static const _kFontFam = 'ModernPictograms';
  static const _kFontPkg = "fluttericon";

  static const IconData search =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_woman =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_pair =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_alt =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam_alt =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circle =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt =
      const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat =
      const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print =
      const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell =
      const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention =
      const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info =
      const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question =
      const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc =
      const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article =
      const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article_alt =
      const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss =
      const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench =
      const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket =
      const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_alt =
      const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alt =
      const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off =
      const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down =
      const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up =
      const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullhorn =
      const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_alt =
      const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full =
      const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small =
      const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in =
      const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out =
      const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popup =
      const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir =
      const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_dir =
      const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_dir =
      const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_dir =
      const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down =
      const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up =
      const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw =
      const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal =
      const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award =
      const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile =
      const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_alt =
      const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet =
      const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ipod =
      const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd =
      const IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid =
      const IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      const IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData easel =
      const IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      const IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart =
      const IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar =
      const IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie =
      const IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar =
      const IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at =
      const IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colon =
      const IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData semicolon =
      const IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squares =
      const IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money =
      const IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      const IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_rect =
      const IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      const IconData(0xf302, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_bird =
      const IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_rect =
      const IconData(0xf314, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      const IconData(0xf315, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
