/// Flutter icons Octicons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Octicons
///      fonts:
///       - asset: fonts/Octicons.ttf
///
///
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Octicons {
  Octicons._();

  static const _kFontFam = 'Octicons';
  static const _kFontPkg = "fluttericon";

  static const IconData arrow_small_left = IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_modified = IconData(0xf302, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xf304, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database = IconData(0xf305, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData markdown = IconData(0xf306, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unverified = IconData(0xf307, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark_github = IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_bulb = IconData(0xf30a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch = IconData(0xf30b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData primitive_dot = IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xf30d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xf30e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_directory = IconData(0xf30f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData versions = IconData(0xf310, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_up = IconData(0xf311, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_closed = IconData(0xf312, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xf313, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xf314, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_commit = IconData(0xf315, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_read = IconData(0xf316, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_push = IconData(0xf317, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis = IconData(0xf318, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xf319, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terminal = IconData(0xf31a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xf31b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasklist = IconData(0xf31c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo = IconData(0xf31d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_lock = IconData(0xf31e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulse = IconData(0xf31f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_down = IconData(0xf320, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xf321, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_ignored = IconData(0xf322, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_submodule = IconData(0xf323, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData primitive_square = IconData(0xf324, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute = IconData(0xf325, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unmute = IconData(0xf326, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outline = IconData(0xf327, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_icon = IconData(0xf328, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaker = IconData(0xf329, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply = IconData(0xf32a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic = IconData(0xf32b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_renamed = IconData(0xf32c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_small = IconData(0xf32d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dash = IconData(0xf32e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_unordered = IconData(0xf32f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xf330, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xf331, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData primitive_dot_stroke = IconData(0xf332, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saved = IconData(0xf333, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unfold = IconData(0xf334, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss = IconData(0xf335, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_small_down = IconData(0xf336, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_arrow_down = IconData(0xf337, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fold = IconData(0xf338, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out = IconData(0xf339, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_opened = IconData(0xf33a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_code = IconData(0xf33b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trashcan = IconData(0xf33c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xf33d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_check = IconData(0xf33e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_template = IconData(0xf33f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbsup = IconData(0xf340, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_x = IconData(0xf341, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_gist = IconData(0xf342, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xf343, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mention = IconData(0xf344, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_download = IconData(0xf345, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_branch = IconData(0xf346, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squirrel = IconData(0xf347, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_download = IconData(0xf348, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kebab_vertical = IconData(0xf349, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_arrow_left = IconData(0xf34a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clippy = IconData(0xf34b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone = IconData(0xf34c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_clone = IconData(0xf34d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workflow = IconData(0xf34e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xf34f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xf350, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plug = IconData(0xf351, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xf352, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xf353, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kebab_horizontal = IconData(0xf354, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_external = IconData(0xf355, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xf356, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xf357, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xf358, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xf359, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph = IconData(0xf35a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_media = IconData(0xf35b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_size = IconData(0xf35c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_newline = IconData(0xf35d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xf35e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf35f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_camera_video = IconData(0xf360, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_added = IconData(0xf361, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_both = IconData(0xf362, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circuit_board = IconData(0xf363, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_pull = IconData(0xf364, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_in = IconData(0xf365, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_closed = IconData(0xf366, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData north_star = IconData(0xf367, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internal_repo = IconData(0xf368, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xf369, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData law = IconData(0xf36a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload = IconData(0xf36b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xf36c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_bars = IconData(0xf36d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flame = IconData(0xf36e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horizontal_rule = IconData(0xf36f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xf370, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xf371, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_template_private = IconData(0xf372, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_action = IconData(0xf373, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcast = IconData(0xf374, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive = IconData(0xf375, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xf376, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData milestone = IconData(0xf377, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project = IconData(0xf378, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_mobile = IconData(0xf379, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_arrow_right = IconData(0xf37a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_small_right = IconData(0xf37b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xf37c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xf37d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_forked = IconData(0xf37e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_arrow_up = IconData(0xf37f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xf380, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jersey = IconData(0xf381, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_desktop = IconData(0xf382, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package = IconData(0xf383, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbsdown = IconData(0xf384, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xf385, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xf386, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dependent = IconData(0xf387, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket = IconData(0xf388, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xf389, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley = IconData(0xf38a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_reopened = IconData(0xf38b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xf38c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirror = IconData(0xf38d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xf38e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_symlink_directory = IconData(0xf38f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData browser = IconData(0xf390, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server = IconData(0xf391, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_right = IconData(0xf392, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_tower = IconData(0xf393, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xf394, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xf395, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_removed = IconData(0xf396, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hubot = IconData(0xf397, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xf398, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gist_secret = IconData(0xf39a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x = IconData(0xf39b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_normal = IconData(0xf39c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infinity = IconData(0xf39d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mortar_board = IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xf39f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf = IconData(0xf3a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workflow_all = IconData(0xf3a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified = IconData(0xf3a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_ordered = IconData(0xf3a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xf3a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_camera = IconData(0xf3a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_changes = IconData(0xf3a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData organization = IconData(0xf3a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xf3a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xf3a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fold_up = IconData(0xf3aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grabber = IconData(0xf3ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip = IconData(0xf3ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_symlink_file = IconData(0xf3ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_binary = IconData(0xf3ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telescope = IconData(0xf3af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_full = IconData(0xf3b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_merge = IconData(0xf3b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fold_down = IconData(0xf3b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = IconData(0xf3b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_slash = IconData(0xf3b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData octoface = IconData(0xf3b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_pull_request = IconData(0xf3b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff = IconData(0xf3b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug = IconData(0xf3b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsaved = IconData(0xf3b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xf3ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xf3bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xf3bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gist = IconData(0xf3bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zap = IconData(0xf3be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_compare = IconData(0xf3bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_left = IconData(0xf3c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_discussion = IconData(0xf3c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_zip = IconData(0xf3c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xf3c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xf3c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote = IconData(0xf3c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard = IconData(0xf3c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paintcan = IconData(0xf3c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xf3c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruby = IconData(0xf3c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_force_push = IconData(0xf3ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_small_up = IconData(0xf3cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
