/// Flutter icons WebSymbols
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WebSymbols
///      fonts:
///       - asset: fonts/WebSymbols.ttf
///
///
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
///
import 'package:flutter/widgets.dart';

class WebSymbols {
  WebSymbols._();

  static const _kFontFam = 'WebSymbols';
  static const _kFontPkg = "fluttericon";

  static const IconData search =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circle =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circle =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circle =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open =
      const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_all =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt =
      const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat =
      const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention =
      const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc =
      const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docs_landscape =
      const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive =
      const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss =
      const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_alt =
      const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog =
      const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout =
      const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block =
      const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full =
      const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full_circle =
      const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popup =
      const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open =
      const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open =
      const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circle =
      const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circle =
      const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circle =
      const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circle =
      const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir =
      const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_dir =
      const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_micro =
      const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_micro =
      const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw_circle =
      const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_cw =
      const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData updown_circle =
      const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target =
      const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal =
      const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_0 =
      const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_1 =
      const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_2 =
      const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_3 =
      const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_4 =
      const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_5 =
      const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_6 =
      const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_7 =
      const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font =
      const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list =
      const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_numbered =
      const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_left =
      const IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_right =
      const IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      const IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terminal =
      const IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_rect =
      const IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_bird =
      const IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplus_rect =
      const IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vkontakte_rect =
      const IconData(0xf30a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype =
      const IconData(0xf30b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData odnoklassniki_rect =
      const IconData(0xf30d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo_rect =
      const IconData(0xf30e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr_rect =
      const IconData(0xf310, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_rect =
      const IconData(0xf312, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      const IconData(0xf313, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
