/// Flutter icons Zocial
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Zocial
///      fonts:
///       - asset: fonts/Zocial.ttf
///
///
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
///
import 'package:flutter/widgets.dart';

class Zocial {
  Zocial._();

  static const _kFontFam = 'Zocial';
  static const _kFontPkg = "fluttericon";

  static const IconData duckduckgo =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aim =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delicious =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flattr =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eventful =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smashmag =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wikipedia =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lanyrd =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fivehundredpx =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w3c =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foursquare =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData html5 =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ie =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call =
      const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grooveshark =
      const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ninetyninedesigns =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forrst =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digg =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guest =
      const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gowalla =
      const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appstore =
      const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger =
      const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc =
      const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble =
      const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData evernote =
      const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr =
      const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viadeo =
      const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instapaper =
      const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weibo =
      const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData klout =
      const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meetup =
      const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vk =
      const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plancast =
      const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disqus =
      const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss =
      const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype =
      const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo =
      const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows =
      const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xing =
      const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yahoo =
      const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome =
      const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email =
      const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData macstore =
      const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myspace =
      const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podcast =
      const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon =
      const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steam =
      const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudapp =
      const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox =
      const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ebay =
      const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled =
      const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplay =
      const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itunes =
      const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plurk =
      const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData songkick =
      const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lastfm =
      const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gmail =
      const IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinboard =
      const IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData openid =
      const IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quora =
      const IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud =
      const IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr =
      const IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eventasaurus =
      const IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wordpress =
      const IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yelp =
      const IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData intensedebate =
      const IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eventbrite =
      const IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scribd =
      const IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData posterous =
      const IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stripe =
      const IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opentable =
      const IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart =
      const IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print =
      const IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angellist =
      const IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      const IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dwolla =
      const IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appnet =
      const IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statusnet =
      const IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData acrobat =
      const IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drupal =
      const IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buffer =
      const IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pocket =
      const IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitbucket =
      const IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lego =
      const IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login =
      const IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow =
      const IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hackernews =
      const IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lkdto =
      const IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
